// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFileToJSON(arg1) {
  return window['go']['main']['App']['AddFileToJSON'](arg1);
}

export function DeleteFileFromJSON(arg1) {
  return window['go']['main']['App']['DeleteFileFromJSON'](arg1);
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function ValidateExcelFile(arg1) {
  return window['go']['main']['App']['ValidateExcelFile'](arg1);
}

export function ValidateImgFiles(arg1) {
  return window['go']['main']['App']['ValidateImgFiles'](arg1);
}
