// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFileToJSON(arg1:string):Promise<boolean>;

export function DeleteFileFromJSON(arg1:string):Promise<boolean>;

export function GetFileSize(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectExcelFile():Promise<main.FileInfo>;

export function SelectFolder():Promise<Array<main.FileInfo>>;

export function ValidateExcelFile(arg1:main.FileInfo):Promise<boolean>;

export function ValidateImgFiles(arg1:Array<main.FileInfo>):Promise<Array<main.FileInfo>>;
